spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true?characterEncoding=utf-8
    username: root
    password: ghy19980313
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.ocean: info
  file:
    name: blog-pro.log
    path: D:\javaProject\log
server:
  port: 8081
